---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: rutuja
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "prutuja10/mini_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name mini_calculator prutuja10/mini_calculator
